export const routes = {
  //Navigator
  AUTH: "Auth",
  //Routes
  SIGN_IN: "Sign In",
  SIGN_UP: "Sign Up",

  //StackNavigatorMain
  MAIN: "Main",
  //Routes
  ADD_WORKOUT: "ADDWORKOUT",
  HOME_WORKOUT: "HOMEWORKOUT",
  COMPANY_HOME: "CompanyHome",
  //AUTH ROUTES
  PEOPLE: "People",

  //StackNavigation for HealthZone
  HEALTH_ZONE: "HEALTHZONE",
  //Routes
  HEALTHZONE_COMPONENT: "HEALTHZONE_COMPONENT",
  //Weights
  WEIGHTS_HOME: "WEIGHTS_HOME",
  ADD_WEIGHT: "ADD_WEIGHT",
  UPDATE_WEIGHT: "UPDATE_WEIGHT",
  //SLEEPS
  SLEEP_HOME: "SLEEP_HOME",
  ADD_SLEEP: "ADD_SLEEP",
  UPDATE_SLEEP: "UPDATE_SLEEP",
  //NUTRITION
  NUTRITION_HOME: "NUTRITION_HOME",
  ADD_NUTRITION: "ADD_NUTRITION",
  UPDATE_NUTRITION: "UPDATE_NUTRITION",

  //TabNavigatorMain
  MAINTAB: "MainTab",
  //Routes
  EXERCISEHOME: "EXERCISEHOME",
};